### ISSUE TITLE
Use cardGrid instead of cardSlider for playlists as an option in the config.json

### ISSUE THREAD

**Issue by buzzguy** [jwplayer/jw-showcase#143]
### Expected Behavior

Use the provided cardGrid layout instead of the cardSlider that is default

New to Angular, so having a little trouble figuring out how to use the cardGrid layout. It would be nice if this could be configured in config.json

- JW Showcase version 3.4

**Comment by ChristiaanScheermeijer** [comment]
Hi @buzzguy,

I like the idea of adding an option to use the card grid component in the dashboard. In your case, do you only want to show a single grid or would you like to add multiple (even between sliders)?

@johnluther @hblee what do you think?

**Comment by johnluther** [comment]
@ChristiaanScheermeijer by dashboard you mean the homepage, right?

I agree, that could be a useful config option. Maybe make it part of the playlist config instead of per-page? Something like content.playlistId.layout: grid | slider?

I would be a bit concerned about page load performance, though. If a site has many playlists (say, 10) all set to to "grid", you will potentially end up with 990 poster images on the page (10 * max of 99 items per playlist). Loading all those images could create a very slow UX. Maybe we could implement lazy loading of images below the fold in those cases?

**Comment by ChristiaanScheermeijer** [comment]
Yes, I mean the homepage :-)

I like the idea of experimenting with multiple content types, these can also be used for banners, ads, single video, etc..

Aforementioned would definitely have a lot of impact on the page load speed. Images are automatically lazy loaded, but generating the DOM for that many cards will even cause more slowdown. Infinite scroll might be an option. This way we can prevent rendering of the items below the fold.

**Comment by johnluther** [comment]
> Infinite scroll might be an option.

Sorry, that's what I actually meant, not lazy loading... :-)

**Comment by buzzguy** [comment]
@ChristiaanScheermeijer yes, on the landing page/homepage, I wanted to use a grid instead of the slider. Perhaps show a max of 5 with a 'see all' button at the end. It would be cool to choose a carousel underneath that too as an option.

**Comment by buzzguy** [comment]
I would also like to use the config for placing a single player that auto-plays mentioned in your earlier comment.

**Comment by ChristiaanScheermeijer** [comment]
Hi @buzzguy, in Release [3.7.1](https://github.com/jwplayer/jw-showcase/releases/tag/v3.7.1) you can use [grids](https://github.com/jwplayer/jw-showcase/blob/master/app/config.json#L40) on the dashboard!

**Comment by buzzguy** [comment]
awesome! thanks 😀
