### ISSUE TITLE
Cordova + Jw showcase

### ISSUE THREAD

**Issue by augmen** [jwplayer/jw-showcase#151]
How to built hybrid apps using cordova with  Jw showcase. Please guide

**Comment by hblee** [comment]
Hi @augmen, 

JW Showcase is currently built with Angular with support for Progressive Web Apps (PWA). We currently do not support building hybrid apps using Cordova.

That being said, there's this article we found that may help you:
https://stackoverflow.com/a/30126569

We'd be happy to link others to your project if you are successful, but please understand though that since we don't support Cordova, we cannot guarantee it will work and cannot anticipate any problems or issues you may encounter.

Good luck!
