### ISSUE TITLE
Autostart not working in self-hosted showcase site

### ISSUE THREAD

**Issue by fsh2** [jwplayer/jw-showcase#179]
### Expected Behavior

When the player is configured for autostart=true, we'd expect the video play automatically when a user visits the video from a desktop using a browser that supports autoplay.

### Actual Behavior

User is required to click play to enforce video playback - autoplay does not work.

### Steps to reproduce

1. Navigate to http://categories.outsidetv.com/m/j67Q71Sf/great-lakes-bad-lines-colin-mccarthy?list=hwJN7JCA
2. Open console and check jwplayer().getConfig()
3.Notice autostart is 'false' despite player settings in JW UI:
{autostart: false, controls: true, displaytitle: true, displaydescription: true, mobilecontrols: false, …}

### Environment

- Macbook Pro
- Mac OS 10.12
- JW Showcase version 3.9

**Comment by pajter** [comment]
Hi @fsh2,

I'm afraid to say that this is actually a feature, not a bug. It was an intentional decision to disable and override the autostart flag in Showcase, following industry best practices. There are currently no plans to provide additional config options to toggle this behavior.

If you're willing to build from source, you can easily edit the code to re-enable autostart in this file for instance: https://github.com/jwplayer/jw-showcase/blob/master/app/scripts/core/directives/player.directive.js#L108

I hope that helps! Let me know if you have questions.
