### ISSUE TITLE
Translation burger menu and recommanded content

### ISSUE THREAD

**Issue by lagardereactive** [jwplayer/jw-showcase#187]
Hi JW Showcase Team, 
i have two simple question (i hope). 
1 : Do you know if it is possible to translate the burger menu and if yes how and where (settings and clear vidéos ...) ? 
2 : i don't know why when i m trying to setup my showcase player with active Discover and at the end of my video i have everytime the next up and no the recommanded content. I actived "on" the recommended content, added a title, selected a playlist and auto-advance setting but nothing, always the next up. 
This is an exemple : https://preview-lclwwtg5.jwpapp.com/

Thank you very much for your help !

**Comment by pajter** [comment]
Hi!

1: Unfortunately we don't yet support translation and/or localization. Currently the only way to do this is by forking the repo and editing the source files.

2: Showcase actively ignores any Player settings except for skinning. This was an intentional decision, as we wanted Showcase to adhere to publisher best practices. Once again, this can be circumvented by building Showcase from source. That gives you the option to re-enable those Player configuration settings by editing a config file.

If you feel like building from source, check out the [wiki page](https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code). It shouldn't take too much time to edit the files you need to edit.

**Comment by lagardereactive** [comment]
Thank you for your help !
