### ISSUE TITLE
Showcase: Crash [Upgrade ?]

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#210]
### Expected Behavior

*Describe expected behavior*
When a user navigates to http://cntvnow.com/gallery/ the showcase should load all the videos. When a video is selected the video should load and the video should play. 

### Actual Behavior

*Describe actual behavior*
None of the videos are loading. When a video is selected a blank screen appears. The title and description sections show {{vm.item.title | limitTo:100 }}

### Steps to reproduce

1. Go to http://cntvnow.com/gallery/ 
2. Click a video 

Is this a result of decommissioning an older version? All of our showcase sites no longer load content. Was a cloud code server retired? Trying to determine root-cause. If the showcase contents are migrated to the newer 3.93 variant, everything works? Why did old versions stop working out of no where? There was no communication about this change. 

### Environment

- *hardware | device*
- *operating system | version*
- *JW Showcase version | url* 3.1.0, lib 3.1.0

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by pajter** [comment]
A number of JavaScript errors are being thrown on your page. You can inspect these in the JS console. Because of these errors the Showcase application can not initialize properly, causing the issues you're describing. This is not something can can fix and/or support.

Please let me know if you have any further questions.

**Comment by akashpatel0427** [comment]
Errors have been inspected. There was no modifications made to the JW JS scripts on our server. Was there a recent code change or decommission on your end that inadvertently broke the script? The example provided was on one site, most of our legacy i.e. 3.x version showcase sites no longer work.

**Comment by rmnl** [comment]
@akashpatel0427 

Last week we released a new version of our feeds service that included changes to the way our thumbnails are included. Support for the new Thumbnail strips has been released with Showcase version 3.4.0.

We recommend upgrading to the latest version and to keep your Showcase up to date because our updates also include security fixes. You can sign up for notifications on new releases via Github.
