### ISSUE TITLE
Enable autoplay on video pages

### ISSUE THREAD

**Issue by jeroenwijering** [jwplayer/jw-showcase#26]
### Expected Behavior

As a viewer, I expect the videos on showcase pages to autoplay, as the only reason I'm visiting a Showcase video page is to watch this video. 

This is similar to how YouTube, Hulu and others work.
### Actual Behavior

One has to click "play" to watch the video, essentially turning the process of watching a video from 1 into 2 steps. 
### Additional Notes

1: With iOS10, it is possible to also play videos inline on iPhone. That completes coverage of "autoplay" scenarios across all major desktop (Safari, Chrome, IE/Edge, Firefox) and mobile (Safari/iOS, Chrome/Android) browsers. 

https://webkit.org/blog/6784/new-video-policies-for-ios/ 

2: Autoplaying videos will hide the metadata that's currently printed over the video. That metadata seems better placed below the video anyway, so it's persistently available and accessible.

**Comment by johnluther** [comment]
We should implement this as a config.json option. A boolean, autoPlay, set to True by default.

**Comment by nvang** [comment]
Just to be sure the current implementation is clear. AutoPlay works when you click the play button; the app will navigate to the video page with autoPlay enabled. When you click the description (or outside the play button) you go to the video page with autoplay disabled. Because of the page navigation (and losing the event) on mobile the video never autoplays when you visit a video page.
