### ISSUE TITLE
Remove descriptions and title on hover. 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#35]
### Expected Behavior

*When you hover of the video no information displays i.e. no description no bottom black bar or title of video. If  the mouse is accidently moved on-top of the video then nothing pops up*

### Actual Behavior

*You move the mouse when you are on top of the video and the description along with the title display and the faded black bar across the bottom appear*

### Steps to reproduce

1. Play a video and hover over it with your mouse. 

----------------------------------------------------------------------------------------

**Comment by johnluther** [comment]
I'm not sure what you are asking. Are you asking for an option to disable the hover-over description and title behavior?

**Comment by akashpatel0427** [comment]
Yes that is correct. We have a client that would like that option.

**Comment by johnluther** [comment]
This seems like something very specific to your requirements, I don't think the feature would get a lot of use in the core product since most people want to display the video titles & descriptions.

So, I would recommend cloning the repo and making this change locally in your source SASS templates (.scss files) , and then rebuilding with grunt to create a new production distribution (/dist/) with the behavior in the CSS stylesheet. See https://github.com/jwplayer/jw-showcase/wiki/Building-from-the-Source-Code for more info on building.

@ChristiaanScheermeijer , can you recommend some SASS changes to get Akash started?

**Comment by ChristiaanScheermeijer** [comment]
Hi @akashpatel0427,

**Replace CSS file (quick)**

Download the precompiled css file from https://we.tl/X335wAx6iZ and replace your current `main.css` with the new `main.css` file. Note that this css file is built for JW Showcase v1.1.0.

**From source**

If you clone the master branch and change these lines:

https://github.com/jwplayer/jw-showcase/blob/master/app/styles/components/_jwVideo.scss#L12
https://github.com/jwplayer/jw-showcase/blob/master/app/styles/components/_jwVideo.scss#L29

from `.jwplayer.jw-state-playing.jw-flag-user-inactive ~, // inactive and playing` 
to `.jwplayer.jw-state-playing ~,  // playing`

After these changes the video overlay will not be shown while the video is playing.
