### ISSUE TITLE
Thumbnail when sharing a video 

### ISSUE THREAD

**Issue by akashpatel0427** [jwplayer/jw-showcase#38]
### Expected Behavior

*When you share a video on facebook the "social-image.jpeg" should appear as a thumbnail*

### Actual Behavior

*The thumbnail is not appearing. *

### Steps to reproduce

1. Go to http://www.theexhibitionschannel.com/video/jB0iIt5N/l49aqk9t
2. Click facebook and notice how it there is only a description and not a thumbnail

**Comment by ChristiaanScheermeijer** [comment]
Since JW Showcase is a single page application it doesn't know about the domain it is served on. Unfortunately the domain is required in the og:image meta tag which is used as image while sharing.

You can fix this by editing the index.html and replace `<meta property="og:image" content="">` with `<meta property="og:image" content="http://www.theexhibitionschannel.com/images/social-image.jpg">`.

**Comment by akashpatel0427** [comment]
Awesome, is there a reason why it works on certain videos but not them all?

Thanks for your help!

**Comment by ChristiaanScheermeijer** [comment]
It could be possible some url's are still cached by Facebook's crawler. You need to 're-fetch' these pages in this tool https://developers.facebook.com/tools/debug/ to fix this.
