### ISSUE TITLE
Double /video/ redirect using S3

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#52]
Example: http://moviepilot.com/video/video/lrYLc95e/Iyfst4Se
We want it to be Example: http://moviepilot.com/video/lrYLc95e/Iyfst4Se

In index.html we have changed the structure to <base href="/video/"> and we have enabled below rule in S3:
```
<RoutingRules>
  <RoutingRule>
    <Condition>
      <KeyPrefixEquals>video/</KeyPrefixEquals>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>yourdomain.com</HostName>
      <ReplaceKeyPrefixWith>video/#/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
```

**Comment by ChristiaanScheermeijer** [comment]
Hi @darjanmilojkovic,

This actually isn't a double redirect. You are using a sub-directory called "video" which is also being used as prefix (identifier) for the video page. If you change the sub-directory to "videos" for example the url would look like this: `http://moviepilot.com/videos/video/lrYLc95e/Iyfst4Se`

We should make a note about this in the documentation, do you agree? @johnluther

**Comment by darjanmilojkovic** [comment]
@ChristiaanScheermeijer how would you suggest we go about fixing this? 

Without adding <base href="**/video/**"> in index.html we run into this issue: {{ rootVm.dataStore.error.message }}.

And the documentation on https://github.com/jwplayer/jw-showcase/wiki/Deploying-jw-showcase suggests that we add: 

```
<RoutingRules>
  <RoutingRule>
    <Condition>
      <KeyPrefixEquals>video/</KeyPrefixEquals>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>yourdomain.com</HostName>
      <ReplaceKeyPrefixWith>video/#/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
```

Which _/video/_ should we omit?

**Comment by johnluther** [comment]
The rules in the documentation is just an example. You can use /videos/ for your subdirectory if you want. Or /content/ or /v/ or any other name that you want.

**Comment by darjanmilojkovic** [comment]
@johnluther I understand we can change it to whatever we want but if a publisher follows the documentation right now the double /video/video/ redirect happens. It's still not clear to me what I should put in the S3 redirect rules to omit the second /video/ in an effort to avoid the `{{ rootVm.dataStore.error.message }}.` error message.

**Comment by ChristiaanScheermeijer** [comment]
In the example configuration we took 'video' as example. We should change
this to prevent further confussion.

If you want to change this you have to change both values in the S3
configuration and also change the `<base href="/video/">` in the index.html

Let me know if you still have issues after these changes.

**Comment by darjanmilojkovic** [comment]
@ChristiaanScheermeijer this is exactly what I have done but still facing the double /video/ issue.

In index.html I have added <base href="/video/"> and in S3 we're using 

`
<RoutingRules>
  <RoutingRule>
    <Condition>
      <KeyPrefixEquals>video/</KeyPrefixEquals>
      <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
    </Condition>
    <Redirect>
      <HostName>yourdomain.com</HostName>
      <ReplaceKeyPrefixWith>video/#/</ReplaceKeyPrefixWith>
    </Redirect>
  </RoutingRule>
</RoutingRules>
`

My question back to you what is causing the double /video/video/ redirect?

**Comment by ChristiaanScheermeijer** [comment]
ok, if you have JW Showcase running in a sub-directory this will be your
base url (e.g. http://mydomain.com/video). When you navigate to the video
page which also includes "video" in the url this will be added to your base
url. This way the application knows which page to load.

http://mydomain.com/video + /video/feedId/mediaId

http://mydomain.com/video + /feed/feedId

If you change your base url to something else it will not show video/video
in the url anymore.

**Comment by darjanmilojkovic** [comment]
If I change the base URL to something else I'll run into the 2nd issue outlined on this page: https://github.com/jwplayer/jw-showcase/wiki/FAQ.

_Q: Why am I getting the error "{{ rootVm.dataStore.error.message }}" when I try to load my site?_

The base URL has to be _<base href="/video/">_ or it'll break. Knowing this, how do I alter the S3 redirect to avoid the double /video/ redirect? I feel that I've only followed the documentation here in an attempt to run JW Showcase in a sub-directory.

**Comment by darjanmilojkovic** [comment]
@ChristiaanScheermeijer btw I see you've been responding over email can you check the thread too on github as I've been editing some of my comments with additional information?

**Comment by johnluther** [comment]
Hi, Darjan. 

I should jump in here explain that this is not a bug. :-) Yes, the documentation could be clearer, I will work on that next week.

**Background**

Showcase _always_ adds /video/ to the content URLs. This is partly due to how single-page web apps like Showcase work (i.e., there are no "real" subdirectories on the server, everything is generated in JavaScript), but it is also to create a logical hierarchy for the content.

If we didn't add /video/, the URLs would look like www.showcase.site/WXu7kuaW/lUGmHThO or www.showcase.site/ACu5kuRn/5KMmHknY, making the site "flat" and very disorganized. But organizing things in these virtual "buckets" enables us to expand functionality like the new deep-linking to playlists in 2.0 (those urls are /feed/).

Probably most important for customers, having descriptive ("hey, this URL is a video!"), consistently-structured URLs is very good for their SEO. Granted, today we use the JW Platform mediaIDs in the paths, which are ugly and not descriptive, but it's the best solution we have for now. In the future I'd like to explore creating URLs at runtime from metadata in the playlist (for example, a cooking video titled "How to boil Swedish crayfish" would create the url how-to-boil-swedish-crayfish), but that could add a lot of overhead to the web app and slow down load times.

So, in a future version, I think a possible solution will be to allow people to configure what they want in their paths instead of "video." This is possible today if you hack the Angular source code, but we want to make Showcase really easy.

For now, would it be okay to use "videos/" as your subdirectory instead of "video/"?

JL

**Comment by darjanmilojkovic** [comment]
@johnluther thanks for clarifying this makes perfect sense now!
