### ISSUE TITLE
Data driven playlists not working

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#58]
I created a data driven playlist in our JW Admin account for JW Showcase but it wasn't able to find it. This broke initialization of the framework due to the "missing playlist". Manual and Dynamic playlists work fine though.

**Comment by ChristiaanScheermeijer** [comment]
Hi @darjanmilojkovic,

Data driven feeds, like the "Default recommendations feed", are not working yet in JW Showcase. Also, since the data driven feeds are generated by using the related_media_id parameter it would require you to add this for each playlist in the config as well. 

**Example URL:**

`http://dashboard.videodock.com/feed.rss?feed_id=or0mFPpE&related_media_id=`

@johnluther @jeroenwijering 
What do you think about Data driven feeds in the JW Showcase dashboard?

**Comment by ChristiaanScheermeijer** [comment]
@darjanmilojkovic a question, are you using a "Trending" playlist or a "Recommendations" feed?

**Comment by jeroenwijering** [comment]
IMO we should offer an option in the config for a "related" feed. If a feed is inserted there, Showcase should load a second shelf in the video details page, above the actual playlist shelf, with these recommendations, tailored to the video playing. 

When the current video playing is done, we auto-advance to the first video in the related feed (NOT the next one in the playlist), mimicking the player's auto-resume behavior. 

At the same time, we should turn related inside the videoplayer off, since (a) the related UI interferes with the Showcase UI and (b) the auto-resume functionality interferes with Showcase properly updating the page slug, metadata and new playlist/related shelves.

**Comment by darjanmilojkovic** [comment]
@ChristiaanScheermeijer I tried using the Trending playlist i.e. _create an automatically updating data-driven playlist from viewer activity_.

**Comment by ChristiaanScheermeijer** [comment]
@jeroenwijering @johnluther Data driven playlists uses a different URL format than regular playlists. It would be nice for the users to not make any difference between these types of playlists. Which allows them to define playlist id's regardless the playlist type. Currently this would only be possible if there is a single URL format available for both.

**Manual / Dynamic URL format**
http://dashboard.videodock.com/feeds/{feed_id}.json

**Trending format URL format**
http://dashboard.videodock.com/feed.json?feed_id={feed_id}

If thats not the case, we could possibly fix this by allowing prefixes (where `dd` stands for data driven) in the configuration and switch the feed URL format based on this prefix.

**Example**

```
"playlists": [
  "WXu7kuaW",
  "Q352cyuc",
  "dd:oR7ahO0J"
]
```

**Comment by jeroenwijering** [comment]
Yes, absolutely. Our related / trending / (and search) feeds are the new and preferred format, but we are still working on getting the manual / dynamic ones onto that new infrastructure. That will happen late Q4, early Q1. Until then, I suggest we disallow trending feeds from being used in Showcase (note in the docs, exclude in the dashboard).

**Comment by johnluther** [comment]
@jeroenwijering , These are still called Trending **playlists** in the dashboard UI, correct? Not feeds?

**Comment by jeroenwijering** [comment]
Correct, that's also an artefact of the underlying technology being used.

Along with unifying the feed format / endpoint, "trending" will simply become a sorting method on dynamic playlists (like "date" or "popularity" or "title")

**Comment by johnluther** [comment]
OK, adding this to the Q4 milestone. 

For now, I will document in the Showcase 2.0 README that Trending playlists and data-driven rec's feeds are not supported.

I will also notify the Portal team of this in their internal Showcase Jira ticket.
