### ISSUE TITLE
Setting up local test environment

### ISSUE THREAD

**Issue by Dean-Coakley** [jwplayer/jw-showcase#71]
Having many issues getting a local test environment working on my machine. This should be possible?

What should base be set to? Currently set to "./" and getting this error.
![jwshowcase](https://cloud.githubusercontent.com/assets/15719653/19172168/507033fc-8c18-11e6-8be7-c187e4a56712.png)

Setting base to "." gives an infinite loading symbol and different error:
![jwshow2](https://cloud.githubusercontent.com/assets/15719653/19172208/86fd53be-8c18-11e6-8a83-696f254376d4.png)

Tested on latest pre built package, correct keys in config.json and on Ubuntu 16.04. I only have one playlist. I should just add it as playlist and delete featured playlist field in json or is this required?

If one was to create pull requests in the future should one make a pull request to the dev branch or the master branch?

**Comment by ChristiaanScheermeijer** [comment]
Hi @Daniel-Berger,

I see you are trying to open JW Showcase without using a webserver. This unfortunately is not possible due to files are being fetched via XHR.

If you want to test the precompiled static app on your local machine you need to have a local webserver like Apache or Nginx. Or if you are familiar with Terminal and have Python installed on your computer (OS X comes shipped with Python) you can run the following commands:

```
$ cd /home/dean/Documents/Programming/precompiled_static_app
$ python -m SimpleHTTPServer 8080
``` 

Now you should have a working webserver on http://localhost:8080

We accept pull requests to the develop branch only and are really appreciated!

Cheers

**Comment by johnluther** [comment]
Thanks, @ChristiaanScheermeijer. I think you meant to address @Dean-Coakley not @Daniel-Berger 

JL

**Comment by Dean-Coakley** [comment]
Hello @ChristiaanScheermeijer 

Thanks very much, it was really easy to test using the provided commands. 

Just before I close this issue: I will likely want to add this to our wordpress site with our websites existing navbar and footer instead of the provided ones. This is possible? Any advice?

**Comment by ChristiaanScheermeijer** [comment]
@johnluther oops! Autocomplete failure...

Good to hear! It is possible to change the header and footer, but will
require some source code modifications. On http://tv.jwplayer.com you can
see an example of creating a static header so it will look like your main
site.

Basicly what you need to do is extract your header and footer HTML and CCS
and add them to the JW Showcase application. All buttons in the header
redirect back to your main site. It will have some disadventages like
menu's not being sync, but it will do the trick :-).

Let me know if you need more information about this approach.
