### ISSUE TITLE
No meta data for specific videos

### ISSUE THREAD

**Issue by darjanmilojkovic** [jwplayer/jw-showcase#80]
When sharing a video from JW Showcase on Facebook we'd like the meta description (og:data) to be unique for each video. Right now it's generic based on the index file.

![fb](https://cloud.githubusercontent.com/assets/4965317/20487161/9ecf1be0-b002-11e6-9953-ac1888dc41c4.png)

Example link: http://moviepilot.com/video/video/yQCn4iIB/Pft3zCfl

**Comment by johnluther** [comment]
I think this would a good enhancement.

**Comment by ChristiaanScheermeijer** [comment]
Hi @darjanmilojkovic,

JW Showcase already populates the meta tags with the correct video metadata, but for must crawlers the response must be 'prerendered' in order to work. This can be done by using a [service](https://prerender.io) or by running the [prerender](https://github.com/prerender/prerender) software yourself.
